"""
Django settings for Transcendance_Back project.

Generated by 'django-admin startproject' using Django 4.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_ROOT = BASE_DIR / 'media'

MEDIA_URL = '/media/'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

load_dotenv()
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '192.168.32.1',
    '169.254.131.21',
    '20.79.107.6',
    'pong42.azurewebsites.net',
    '127.0.0.1',
    'pong42.vercel.app',
    'four2trans-backend.onrender.com', 
    'localhost:3000',
    'c3r1p1.42vienna.com',
    'c3r1p5.42vienna.com',
    'c3r1p2.42vienna.com',
    'c3r1p3.42vienna.com',
    '10.13.1.5',
    '10.13.1.1',
    'localhost:5500',
    'localhost:8443',
    'localhost:443',
    'localhost:8000',
    'ehab42.vercel.app',
    '42transcendence.vercel.app',
    'eelasam.vercel.app',
    'ehab42.vercel.app:8443',
    '42transcendence.vercel.app:8443',
    'eelasam.vercel.app:8443',
    'localhost:8080',
    'api.intra.42.fr',
    'transcendence-beige.vercel.app',
    'backend',
    'frontend',
]


# Application definition

INSTALLED_APPS = [
    'Transcendance',
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'channels',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    #'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'Transcendance_Back.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'Transcendance/templates/transcendance')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

#WSGI_APPLICATION = 'Transcendance_Back.wsgi.application'

ASGI_APPLICATION = 'Transcendance_Back.asgi.application'

CHANNEL_LAYERS = { 
    'default' : { 
        'BACKEND' : "channels.layers.InMemoryChannelLayer"
     } 
}


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv("DB_NAME"),
        'USER': os.getenv("DB_USER"),
        'PASSWORD': os.getenv("DB_PASSWORD"),
        'HOST': os.getenv("DB_HOST"),
        'PORT': os.getenv("DB_PORT"),
    }
}

AUTH_USER_MODEL = 'Transcendance.User'

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'fr'

LANGUAGES = [
    ('fr', 'French'),
    ('en', 'English'),
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "staticfiles/Transcendance/",
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = ['Transcendance.management.commands.email_backend.EmailBackend']

CSRF_TRUSTED_ORIGINS = [
    'http://localhost',
    'https://localhost',
    'http://localhost:8443',
    'https://localhost:8443',
    'https://localhost:443',
    'https://10.13.1.1:8443',
    'https://10.13.1.2:8443',
    'https://10.13.1.3:8443',
    'https://10.13.1.4:8443',
    'https://10.13.1.5:8443',
    'https://10.13.1.5',
    'http://127.0.0.1',
    'https://127.0.0.1:8000',
    'https://127.0.0.1',
    'http://127.0.0.1:5500',
    'https://pong42.vercel.app',
    'https://ehab42.vercel.app',
    'https://42transcendence.vercel.app',
    'https://eelasam.vercel.app',
    'https://ehab42.vercel.app:8443',
    'https://42transcendence.vercel.app:8443',
    'https://eelasam.vercel.app:8443',
    'http://pong42.vercel.app',
    'http://pong42.azurewebsites.net',
    'https://pong42.azurewebsites.net',
    'http://localhost:3000',
    'http://localhost:5500',
    'https://transcendence-beige.vercel.app',
    'https://api.intra.42.fr',
    'https://c3r1p1.42vienna.com',
    'https://c3r1p3.42vienna.com',
    'https://c3r1p4.42vienna.com',
    'https://c3r1p5.42vienna.com',
    'https://c3r1p1.42vienna.com:8443',
    'https://c3r1p3.42vienna.com:8443',
    'https://c3r1p4.42vienna.com:8443',
    'https://c3r1p5.42vienna.com:8443',
    'https://192.168.32.1',
    'https://169.254.131.21',
    'https://20.79.107.6',
    'http://169.254.131.21',
    'http://20.79.107.6'
]

CORS_ALLOWED_ORIGINS = [
    'https://192.168.32.1',
    'http://localhost:8080',
    'http://localhost',
    'https://localhost',
    'http://localhost:8443',
    'https://localhost:8443',
    'https://localhost:443',
    'http://127.0.0.1',
    'https://127.0.0.1:8000',
    'https://127.0.0.1',
    'https://10.13.1.1:8443',
    'https://10.13.1.1',
    'https://10.13.1.2:8443',
    'https://10.13.1.3:8443',
    'https://10.13.1.4:8443',
    'https://10.13.1.5:8443',
    'https://10.13.1.5',
    'https://c3r1p1.42vienna.com',
    'https://c3r1p3.42vienna.com',
    'https://c3r1p4.42vienna.com',
    'https://c3r1p5.42vienna.com',
    'https://c3r1p1.42vienna.com:8443',
    'https://c3r1p3.42vienna.com:8443',
    'https://c3r1p4.42vienna.com:8443',
    'https://c3r1p5.42vienna.com:8443',
    'http://127.0.0.1:5500',
    'https://ehab42.vercel.app',
    'https://42transcendence.vercel.app',
    'https://eelasam.vercel.app',
    'https://ehab42.vercel.app:8443',
    'https://42transcendence.vercel.app:8443',
    'https://eelasam.vercel.app:8443',
    'https://pong42.vercel.app',
    'http://pong42.vercel.app',
    'http://pong42.azurewebsites.net',
    'https://pong42.azurewebsites.net',
    'http://localhost:3000',
    'http://localhost:5500',
    'https://transcendence-beige.vercel.app',
    'https://api.intra.42.fr',
    'https://169.254.131.21',
    'https://20.79.107.6',
    'http://169.254.131.21',
    'http://20.79.107.6'
]

CORS_ORIGIN_ALLOW_ALL = True

CSRF_TRUSTED_ORIGINS = ['https://localhost']

SESSION_COOKIE_SECURE = False