services:
  backend:
    container_name: backend
    restart: on-failure:5
    build:
      context: Transcendance_Back
      dockerfile: Dockerfile
    volumes:
      - ./Transcendance_Back:/app/
      - ./Transcendance_Back/media:/app/media/
    ports:
      - '8000:8000'
    env_file:
      - .env

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: on-failure:5
    volumes:
      - database-postgres:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    env_file:
      - .env

  nginx:
    container_name: nginx
    restart: on-failure:5
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./Transcendance_Back/staticfiles:/app/staticfiles/
    depends_on:
      - backend


volumes:
  database-postgres:

      
networks:
  transcendence:
    name: transcendence
    driver: bridge