# Generated by Django 4.2.9 on 2024-02-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transcendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashmap',
            name='_id',
            field=models.IntegerField(default=0),
        ),
    ]
