# Generated by Django 4.2.10 on 2024-06-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transcendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamehistory',
            name='p1_has_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='p2_has_leave',
            field=models.BooleanField(default=False),
        ),
    ]
