# Generated by Django 4.2.10 on 2024-06-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transcendance', '0003_gamehistory_loser_gamehistory_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_in_PFC',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_in_pong',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_online',
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='Hors Ligne', max_length=200),
        ),
    ]
