# Generated by Django 4.2.10 on 2024-05-23 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Transcendance', '0020_alter_gamehistory_player2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamehistory',
            name='player2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player2', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ponghistory',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player2_pong', to=settings.AUTH_USER_MODEL),
        ),
    ]
