# Generated by Django 4.2.10 on 2024-05-23 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Transcendance', '0021_alter_gamehistory_player2_alter_ponghistory_player2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponghistory',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_winner_pong', to=settings.AUTH_USER_MODEL),
        ),
    ]
