# Generated by Django 4.2.10 on 2024-05-27 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transcendance', '0022_alter_ponghistory_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matchmaking_Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_in_queue', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
