# Generated by Django 4.2.10 on 2024-05-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transcendance', '0023_matchmaking_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='main_queue_player',
            field=models.BooleanField(default=False),
        ),
    ]
