# Generated by Django 4.2.10 on 2024-05-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transcendance', '0025_remove_conversation_conversation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='conversation_id',
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_general',
            field=models.BooleanField(default=False),
        ),
    ]
